
["Sword Stats"]
	#Attack speed of Vibranium Sword | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumSword = 0.5
	#Attack damage of Vibranium Sword | Default Value = 10
	#Range: > 0
	attackDamageVibraniumSword = 10

["Tool Tier Base Properties"]
	#Speed value of Vibranium Tool Tier | Default Value = 30
	#Range: > 0
	speedVibraniumTier = 30
	#Whether Vibranium is unbreakable | Default Value = false
	unbreakableVibranium = false
	#Bonus attack damage for Vibranium Tool Tier | Default Value = 1
	#Range: > 0
	attackDamageBonusVibraniumTier = 1
	#Enchantment value for Vibranium Tool Tier | Default Value = 55
	#Range: > 0
	enchantmentValueVibraniumTier = 55
	#Durability of Vibranium tools | Default Value = 2562
	#Range: > 0
	durabilityVibranium = 2562

["Hammer Stats"]
	#Hammering radius for Vibranium Hammer | Default = 1
	#Range: > 0
	radiusVibraniumHammer = 1
	#Attack damage of Vibranium Hammer | Default Value = 7
	#Range: > 0
	attackDamageVibraniumHammer = 7
	#Attack speed of Vibranium Hammer | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumHammer = 0.5

["Hoe Stats"]
	#Attack damage of Vibranium Hoe | Default Value = 7
	#Range: > 0
	attackDamageVibraniumHoe = 7
	#Attack speed of Vibranium Hoe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumHoe = 0.5

["Paxel Stats"]
	#Attack damage of Vibranium Paxel | Default Value = 11
	#Range: > 0
	attackDamageVibraniumPaxel = 11
	#Attack speed of Vibranium Paxel | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumPaxel = 0.5

["Axe Stats"]
	#Attack damage of Vibranium Axe | Default Value = 12
	#Range: > 0
	attackDamageVibraniumAxe = 12
	#Attack speed of Vibranium Axe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumAxe = 0.5

["Pickaxe Stats"]
	#Attack damage of Vibranium Pickaxe | Default Value = 7
	#Range: > 0
	attackDamageVibraniumPickaxe = 7
	#Attack speed of Vibranium Pickaxe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumPickaxe = 0.5

["Armor Protection and Resistance"]
	#Protection value for Vibranium Boots | Default Value = 6
	#Range: > 0
	protectionValueVibraniumBoots = 6
	#Protection Value for Horse Armor | Default Value = 12
	#Range: > 0
	protectionValueVibraniumHorseArmor = 12
	#Toughness value for Vibranium Armor | Default Value = 3
	#Range: > 0
	toughnessValueVibraniumArmor = 3
	#Protection value for Vibranium Leggings | Default Value = 9
	#Range: > 0
	protectionValueVibraniumLeggings = 9
	#Protection value for Vibranium Chestplate | Default Value = 12
	#Range: > 0
	protectionValueVibraniumChestplate = 12
	#Enchantment value for Vibranium Armor | Default Value = 55
	#Range: > 0
	enchantmentValueVibraniumArmor = 55
	#Protection value for Vibranium Helmet | Default Value = 6
	#Range: > 0
	protectionValueVibraniumHelmet = 6
	#Knockback resistance for Vibranium Armor | Default Value = 0.2
	#Range: 0.0 ~ 1.7976931348623157E308
	knockbackResistanceValueVibraniumArmor = 0.20000000298023224

["Armor Special Effects and Abilities"]
	#Whether Vibranium Armor allows walking on Powdered Snow | Default Value = true
	canWalkOnPowderedSnowVibranium = true
	#Whether Vibranium Armor gives Night Vision | Default Value = true
	nightVisionVibraniumArmor = true
	#Whether Vibranium Armor gives Jump I | Default Value = true
	jumpIVibraniumArmor = true
	#Whether Vibranium Armor gives Speed I | Default Value = true
	speedIVibraniumArmor = true

["Excavator Stats"]
	#Excavation radius for Vibranium Excavator | Default = 1
	#Range: > 0
	radiusVibraniumExcavator = 1
	#Attack speed of Vibranium Excavator | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumExcavator = 0.5
	#Attack damage of Vibranium Excavator | Default Value = 7
	#Range: > 0
	attackDamageVibraniumExcavator = 7

["Bow Settings"]
	#Enchantment value for Vibranium Bow | Default Value = 5
	#Range: > 0
	enchantmentValueVibraniumBow = 5
	#Arrow count for Vibranium Bow | Default = 2
	#Range: > 0
	arrowCountVibraniumBow = 2
	#Damage of Vibranium Bow | Default Value = 5
	#Range: > 0
	damageVibraniumBow = 5

["Shovel Stats"]
	#Attack damage of Vibranium Shovel | Default Value = 7
	#Range: > 0
	attackDamageVibraniumShovel = 7
	#Attack speed of Vibranium Shovel | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVibraniumShovel = 0.5

