
["Sword Stats"]
	#Attack damage of Vulpus Sword | Default Value = 14
	#Range: > 0
	attackDamageVulpusSword = 14
	#Attack speed of Vulpus Sword | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusSword = 0.5

["Tool Tier Base Properties"]
	#Enchantment value for Vulpus Tool Tier | Default Value = 65
	#Range: > 0
	enchantmentValueVulpusTier = 65
	#Bonus attack damage for Vulpus Tool Tier | Default Value = 3
	#Range: > 0
	attackDamageBonusVulpusTier = 3
	#Whether Vulpus is unbreakable | Default Value = false
	unbreakableVulpus = false
	#Speed value of Vulpus Tool Tier | Default Value = 40
	#Range: > 0
	speedVulpusTier = 40
	#Durability of Vulpus tools | Default Value = 3093
	#Range: > 0
	durabilityVulpus = 3093

["Hammer Stats"]
	#Attack speed of Vulpus Hammer | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusHammer = 0.5
	#Radius of Vulpus Hammer effect | Default Value = 2
	#Range: > 0
	radiusVulpusHammer = 2
	#Attack damage of Vulpus Hammer | Default Value = 11
	#Range: > 0
	attackDamageVulpusHammer = 11

["Hoe Stats"]
	#Attack damage of Vulpus Hoe | Default Value = 10
	#Range: > 0
	attackDamageVulpusHoe = 10
	#Attack speed of Vulpus Hoe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusHoe = 0.5

["Paxel Stats"]
	#Attack speed of Vulpus Paxel | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusPaxel = 0.5
	#Attack damage of Vulpus Paxel | Default Value = 15
	#Range: > 0
	attackDamageVulpusPaxel = 15

["Axe Stats"]
	#Attack damage of Vulpus Axe | Default Value = 15
	#Range: > 0
	attackDamageVulpusAxe = 15
	#Attack speed of Vulpus Axe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusAxe = 0.5

["Pickaxe Stats"]
	#Attack speed of Vulpus Pickaxe | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusPickaxe = 0.5
	#Attack damage of Vulpus Pickaxe | Default Value = 10
	#Range: > 0
	attackDamageVulpusPickaxe = 10

["Armor Protection and Resistance"]
	#Protection value for Vulpus Helmet | Default Value = 9
	#Range: > 0
	protectionValueVulpusHelmet = 9
	#Toughness value for Vulpus Armor | Default Value = 7
	#Range: > 0
	toughnessValueVulpusArmor = 7
	#Protection value for Vulpus Boots | Default Value = 9
	#Range: > 0
	protectionValueVulpusBoots = 9
	#Knockback resistance for Vulpus Armor | Default Value = 0.3
	#Range: 0.0 ~ 1.7976931348623157E308
	knockbackResistanceValueVulpusArmor = 0.30000001192092896
	#Protection value for Vulpus Leggings | Default Value = 12
	#Range: > 0
	protectionValueVulpusLeggings = 12
	#Protection value for Vulpus Chestplate | Default Value = 16
	#Range: > 0
	protectionValueVulpusChestplate = 16
	#Enchantment value for Vulpus Armor | Default Value = 65
	#Range: > 0
	enchantmentValueVulpusArmor = 65
	#Protection value for Horse Armor | Default Value = 16
	#Range: > 0
	protectionValueVulpusHorseArmor = 16

["Armor Special Effects and Abilities"]
	#Whether Vulpus Armor gives Jump II | Default Value = true
	jumpIIVulpusArmor = true
	#Whether Vulpus Armor gives Speed II | Default Value = true
	speedIIVulpusArmor = true
	#Whether Vulpus Armor allows walking on Powdered Snow | Default Value = true
	canWalkOnPowderedSnowVulpus = true
	#Whether Vulpus Armor makes Piglins Neutral | Default Value = true
	makesPiglinsNeutralVulpus = true
	#Whether Vulpus Armor gives Night Vision | Default Value = true
	nightVisionVulpusArmor = true
	#Whether Vulpus Armor prevents Hunger loss | Default Value = true
	neverLoseHungerVulpusArmor = true
	#Whether Vulpus Armor gives Immunity to Fall Damage | Default Value = true
	immuneToFallDamageVulpusArmor = true
	#Whether Vulpus Armor gives Fire Resistance | Default Value = true
	fireResistanceVulpusArmor = true

["Excavator Stats"]
	#Radius of Vulpus Excavator effect | Default Value = 2
	#Range: > 0
	radiusVulpusExcavator = 2
	#Attack speed of Vulpus Excavator | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusExcavator = 0.5
	#Attack damage of Vulpus Excavator | Default Value = 11
	#Range: > 0
	attackDamageVulpusExcavator = 11

["Bow Settings"]
	#Enchantment value for Vulpus Bow | Default Value = 5
	#Range: > 0
	enchantmentValueVulpusBow = 5
	#Damage of Vulpus Bow | Default Value = 10
	#Range: > 0
	damageVulpusBow = 10
	#Arrow count for Vulpus Bow | Default = 3
	#Range: > 0
	arrowCountVulpusBow = 3

["Shovel Stats"]
	#Attack damage of Vulpus Shovel | Default Value = 10
	#Range: > 0
	attackDamageVulpusShovel = 10
	#Attack speed of Vulpus Shovel | Default Value = 0.5
	#Range: 0.0 ~ 1024.0
	attackSpeedVulpusShovel = 0.5

